# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

name: text_indexing
description: Dart library for creating an inverted index on a collection of text documents.
version: 0.8.0
repository: https://github.com/GM-Consult-Pty-Ltd/text_indexing
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/text_indexing/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----
  collection: ^1.16.0
  meta: ^1.8.0
  rxdart: ^0.27.1 
  text_analysis: ^0.6.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
